services:
  - type: web
    name: chef-asia-backend
    env: docker
    plan: free
    buildCommand: "composer install --no-dev --optimize-autoloader"
    startCommand: "apache2-foreground"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://chef-asia-backend.onrender.com 