services:
  - type: web
    name: chef-asia-backend
    env: docker
    plan: free
    buildCommand: ""
    startCommand: "php artisan serve --host=0.0.0.0 --port=80"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
