services:
  - type: web
    name: chef-asia-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    startCommand: php artisan serve --host=0.0.0.0 --port=8000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://chef-asia-backend.onrender.com
